name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Store signatures in a remote repository (optional)
          # PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/steveseguin/ssn_app/blob/main/CLA.md'
          branch: 'cla-signatures'
          allowlist: 'steveseguin,bot*'
          
          # Optional parameters
          remote-organization-name: '' # enter the remote organization name if storing signatures remotely
          remote-repository-name: '' # enter the remote repository name if storing signatures remotely
          create-file-commit-message: 'Creating file for storing CLA Signatures'
          signed-commit-message: 'CLA Signature for $contributorName (#$pullRequestNo)'
          custom-notsigned-prcomment: 'Thank you for your submission! Before we can merge your contribution, we need you to sign our Contributor License Agreement (CLA). 
          
          Please visit the following link to read and sign the CLA: [CLA Document](https://github.com/steveseguin/ssn_app/blob/main/CLA.md)
          
          Once you have read the CLA, please comment below with:
          ```
          I have read the CLA Document and I hereby sign the CLA
          ```
          
          You can also sign the CLA by printing, signing, scanning, and emailing it to steve@seguin.email.'
          custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          custom-allsigned-prcomment: '✅ All contributors have signed the CLA!'